src
    components
        layouts
            Layout.tsx
        ui
            Navbar.tsx
        users
            UserTable.tsx
    interfaces
        user-list.ts
    pages
        api
            gymApi.ts
            
        _app.tsx
        _document.tsx
        index.tsx
        pageone.tsx
        pagetwo.tsx
        pagethree.tsx
    styles
        global.css
    themes
        theme-dark.ts
        theme-light.ts